[build]
builder = "NIXPACKS"

[build.env]
POETRY_VIRTUALENVS_CREATE = "true"
POETRY_VIRTUALENVS_IN_PROJECT = "false"

[deploy]
startCommand = "poetry install --no-interaction --no-ansi && poetry run task run"
